# Generated by Django 4.1.2 on 2022-10-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='desctiption',
            new_name='description',
        ),
    ]
